dist: trusty
sudo: required

services:
  - docker

before_install:
  - docker pull kornicameister/resume-cli:latest
script:
  - docker run --rm -it -v $(pwd):/app -w /app kornicameister/resume-cli:latest resume test

deploy:
  provider: releases
  api_key:
    secure: XibTG1omV4Gjkn3JgGN4OvJ9MgN3VoDIlNAsV/s4Xxj1TRKSajzoZ7PIQVSi1W1euPf91U3OqSodtvEtIFhf+9r3IEIRMdH46eec95snIYXta8rKhCDaEWvolAtY8WpE+OG3CtufpIFAKrjzB2JYsTEeCjNigMFwj2HP4yOK4ege3cU4h7NAto+eaDjZteNQTKKJa5hWlNORqTFXd6Ab1AlZ5UyccW9bZu5FTXYA1Gm3tAzpUHlYt2+q8mCKR0De43e+Xn97ZIjT28CN7eh0eTPtOs6Vo8TM+MO2fSWDou+ZO0qiuFiLpamrKFX2hSAOhwiPUVYYDh9H8aQ6D7JWhTwxpEHsDniaxbCbdlrQ/zdxZhg+s+QEFkVqdkjbzyVykV1iQAPtJGQI4VSCper0Nzrp+tOwKFkWYFcM9TwXGbYIGGdU9dg75erRqYMBWWenrsfrdbXy6UDgKA1SVREngJ2UavGBQQ2CDhMVXTDYuLaBW231b+w1HeCgnJpu0LH7U/VlVXZVNrr3X6ANhRAKIWUZdl/B+//dvasDMBeefYi3onC9rgdlFUil8uSxF7eCitTb/8vtUjBaBkIfmmpXAfM55K57FR8vk8eW9+ZwCpjvgC8x5666rbX0lcdIN34xVu/AVlUWG4znfk7Z5U0i3kt6XPDBUkulQzdliJqCrK4=
  file:
    - cv.pdf
  skip_cleanup: true
  on:
    tags: true
