dist: trusty
sudo: required

services:
  - docker

before_install:
- docker pull harshjv/texlive-2015

script:
- docker run --rm -it -v $(pwd):/var/texlive harshjv/texlive-2015 xelatex cv.tex

deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
  - _build/cv.pdf
  skip_cleanup: true
  on:
    tags: true
