dist: trusty
sudo: required

addons:
  apt:
    packages:
    - texlive-full
    - texlive-latex-extra

script:
- wget http://math.sut.ac.th/lab/software/texlive/texmf-dist/tex/latex/unicode-math/unicode-math.sty
- mkdir _build
- xelatex -output-directory _build cv.tex

deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
  - _build/cv.pdf
  skip_cleanup: true
  on:
    tags: true
