---
version: 2.1

orbs:
  github-release: haskell-works/github-release@1.3.3

jobs:
  build:
    working_directory: ~/cv
    machine: true

    steps:
      - checkout
      - run:
          name: Build PDF
          command: make cv.pdf
          persist_to_workspace:
            root: /tmp/build
            paths:
              - ./build/cv.pdf
      - run:
          name: Build JSON
          command: make cv.json
          persist_to_workspace:
            root: /tmp/build
            paths:
              - ./build/cv.json
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - github-release/release:
          tag: $CIRCLE_TAG
          title: Release $CIRCLE_TAG
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          github-token: $DEPLOY_KEY
          checkout: true
          attach-workspace: true
          artefacts-folder: /tmp/build
